/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // documentationSidebar: [{ type: "autogenerated", dirName: "." }],

  documentationSidebar: [
    "introduction",
    {
      type: "autogenerated",
      dirName: "the-outpost-platform",
    },
    {
      type: "category",
      label: "Applications",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Outpost",
          link: {
            type: "doc",
            id: "outpost/outpost",
          },
          items: [
            {
              type: "category",
              label: "Features",
              link: {
                type: "generated-index",
              },
              items: [
                {
                  type: "autogenerated",
                  dirName: "outpost/features",
                },
              ],
            },
            {
              type: "category",
              label: "Developers guide",
              link: {
                type: "generated-index",
              },
              items: [
                {
                  type: "autogenerated",
                  dirName: "outpost/developers",
                },
              ],
            },
            {
              type: "category",
              label: "Admin interface",
              link: {
                type: "generated-index",
              },
              items: [
                {
                  type: "autogenerated",
                  dirName: "outpost/admin",
                },
              ],
            },
            {
              type: "category",
              label: "Service owners interface",
              link: {
                type: "generated-index",
              },
              items: [
                {
                  type: "autogenerated",
                  dirName: "outpost/service-owners",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Outpost API Service",
          link: {
            type: "doc",
            id: "outpost-api-service/outpost-api-service",
          },
          items: [
            {
              type: "category",
              label: "Features",
              link: {
                type: "generated-index",
              },
              items: [
                {
                  type: "autogenerated",
                  dirName: "outpost-api-service/features",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Scout",
          link: {
            type: "doc",
            id: "scout/scout",
          },
          items: [],
        },
        {
          type: "category",
          label: "Find a childminder",
          link: {
            type: "doc",
            id: "find-a-childminder/find-a-childminder",
          },
          items: [],
        },
      ],
    },

    {
      type: "category",
      label: "Tools",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Outpost Design System",
          link: {
            type: "doc",
            id: "outpost-design-system/outpost-design-system",
          },
          items: [],
        },
        {
          type: "category",
          label: "Outpost oAuth",
          link: {
            type: "doc",
            id: "outpost-oauth/outpost-oauth",
          },
          items: [],
        },
      ],
    },

    {
      type: "category",
      label: "Utilities",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Ofsted feed client",
          link: {
            type: "doc",
            id: "ofsted-feed-client/ofsted-feed-client",
          },
          items: [],
        },
      ],
    },

    {
      type: "category",
      label: "The project",
      link: {
        type: "generated-index",
        slug: "/the-project",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "the-project",
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
